# Generated by Django 4.2.23 on 2025-12-14 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='job_provider_profiles/')),
                ('company_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('company_overview', models.TextField(blank=True, null=True)),
                ('job_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('remote', 'Remote')], default='full-time', max_length=20)),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('education', 'Education')], default='technology', max_length=20)),
                ('country', models.CharField(choices=[('usa', 'United States'), ('canada', 'Canada'), ('uk', 'United Kingdom')], default='usa', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Provider Profile',
                'verbose_name_plural': 'Job Provider Profiles',
            },
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('professional_title', models.CharField(blank=True, max_length=100, null=True)),
                ('hourly_rate', models.CharField(blank=True, choices=[('30', '$30/hr'), ('40', '$40/hr'), ('50', '$50/hr'), ('60', '$60/hr'), ('70', '$70/hr')], max_length=10, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('mid', 'Mid'), ('senior', 'Senior')], max_length=10, null=True)),
                ('specialization', models.CharField(blank=True, choices=[('web-dev', 'Web Development'), ('design', 'Design'), ('marketing', 'Marketing')], max_length=20, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills', null=True)),
                ('country', models.CharField(blank=True, choices=[('uae', 'UAE'), ('uk', 'UK'), ('usa', 'USA'), ('india', 'India')], max_length=20, null=True)),
                ('city', models.CharField(blank=True, choices=[('dubai', 'Dubai'), ('london', 'London'), ('new-york', 'New York'), ('toronto', 'Toronto')], max_length=20, null=True)),
                ('language', models.CharField(blank=True, choices=[('english', 'English'), ('arabic', 'Arabic'), ('french', 'French'), ('spanish', 'Spanish')], max_length=20, null=True)),
                ('language_proficiency', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('fluent', 'Fluent')], max_length=20, null=True)),
                ('linkedin_or_github', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('education', models.JSONField(blank=True, default=list, help_text="A list of education entries, e.g., [{'degree': 'B.Sc.', 'school': 'MIT', 'start_year': '2018', 'end_year': '2022', 'description': '...'}]", null=True)),
                ('work_experience', models.JSONField(blank=True, default=list, help_text="A list of work experience entries, e.g., [{'job_title': 'UX Designer', 'company': 'Dropbox', 'start_year': '2020', 'end_year': '2022', 'description': '...'}]", null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
