# Generated by Django 4.2.23 on 2025-12-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_freelancerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freelancerprofile',
            options={'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterModelOptions(
            name='jobproviderprofile',
            options={'verbose_name': 'Employer', 'verbose_name_plural': 'Employers'},
        ),
    ]
