# Generated by Django 4.2.23 on 2025-12-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_freelancerprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='role_fillter',
            field=models.CharField(default='freelancer', max_length=20),
        ),
    ]
