# Generated by Django 4.2.23 on 2025-12-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='milestonepayment',
            name='payment_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(default='fixed_price', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.CharField(default='public', max_length=50),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(default='submitted', max_length=50),
        ),
    ]
