# Generated by Django 4.2.23 on 2025-12-18 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='service',
            name='sub_heading',
        ),
        migrations.RemoveField(
            model_name='service',
            name='sub_heading_content',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='description',
        ),
        migrations.CreateModel(
            name='ServiceSubHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_headings', to='cms.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
