# Generated by Django 4.2.23 on 2025-12-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_id', models.IntegerField(help_text='Foreign key to freelancer_profile.id')),
                ('resume', models.FileField(blank=True, help_text='Resume file upload', null=True, upload_to='resumes/')),
                ('cover_letter', models.TextField(help_text='Cover letter submitted by freelancer')),
                ('expected_rate', models.DecimalField(blank=True, decimal_places=2, help_text="Freelancer's expected rate", max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Save for Later', 'Save for Later'), ('Withdrawn', 'Withdrawn')], default='Pending', help_text='Application status (Pending, Accepted, Rejected, Save for Later, Withdrawn)', max_length=20)),
                ('date_applied', models.DateTimeField(auto_now_add=True, help_text='Date the freelancer applied')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Rating from 1 to 5', max_digits=2, null=True)),
                ('comments', models.TextField(blank=True, help_text='Comments from job provider review', null=True)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'db_table': 'job_application',
                'ordering': ['-date_applied'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Job title', max_length=255)),
                ('department', models.CharField(help_text='Department or team the job belongs to', max_length=100)),
                ('job_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary')], help_text='Job type', max_length=50)),
                ('work_location', models.CharField(help_text='Work area', max_length=255)),
                ('work_mode', models.CharField(choices=[('on-site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], help_text='Mode of work', max_length=20)),
                ('role_overview', models.TextField(help_text='Overview of the job role')),
                ('key_responsibilities', models.TextField(help_text='List of key responsibilities')),
                ('required_qualifications', models.TextField(help_text='Minimum qualifications required')),
                ('preferred_qualifications', models.TextField(blank=True, help_text='Preferred qualifications', null=True)),
                ('languages_required', models.CharField(blank=True, help_text='Required languages', max_length=255, null=True)),
                ('job_category', models.CharField(choices=[('engineering', 'Engineering'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('human resources', 'Human Resources'), ('finance', 'Finance'), ('operations', 'Operations'), ('design', 'Design'), ('product', 'Product'), ('customer-support', 'Customer Support'), ('other', 'Other')], help_text='Job category', max_length=100)),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary', max_digits=10, null=True)),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary', max_digits=10, null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('AED', 'AED'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='USD', help_text='Currency', max_length=3)),
                ('application_deadline', models.DateTimeField(blank=True, help_text='Deadline to apply', null=True)),
                ('application_method', models.CharField(choices=[('portal', 'Portal'), ('email', 'Email')], default='portal', help_text='Application method', max_length=20)),
                ('interview_mode', models.CharField(choices=[('in-person', 'In-person'), ('zoom', 'Zoom'), ('phone', 'Phone'), ('hybrid', 'Hybrid')], help_text='Interview mode', max_length=20)),
                ('hiring_manager', models.CharField(help_text='Name of the hiring manager', max_length=255)),
                ('number_of_openings', models.IntegerField(default=1, help_text='Number of open positions')),
                ('expected_start_date', models.DateTimeField(blank=True, help_text='Expected start date', null=True)),
                ('screening_questions', models.TextField(blank=True, help_text='Screening questions for applicants', null=True)),
                ('file_upload', models.URLField(blank=True, help_text='URL for job-related file upload', null=True)),
                ('health_insurance', models.BooleanField(default=False, help_text='Health insurance offered?')),
                ('remote_work', models.BooleanField(default=False, help_text='Remote work allowed?')),
                ('paid_leave', models.BooleanField(default=False, help_text='Paid leave offered?')),
                ('bonus', models.BooleanField(default=False, help_text='Bonus offered?')),
                ('date_posted', models.DateTimeField(auto_now_add=True, help_text='Date the job was posted')),
                ('job_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('filled', 'Filled'), ('paused', 'Paused')], default='open', help_text='Job status', max_length=20)),
                ('job_provider', models.ForeignKey(help_text='Foreign key to profiles.JobProviderProfile', on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='profiles.jobproviderprofile')),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'db_table': 'job_posting',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Pending', help_text='Status of the offer (Pending, Accepted, Rejected)', max_length=20)),
                ('offer_details', models.TextField(help_text='Detailed offer (salary, benefits, etc.)')),
                ('date_offered', models.DateTimeField(auto_now_add=True, help_text='Date the offer was made')),
                ('date_accepted', models.DateTimeField(blank=True, help_text='Date the offer was accepted (nullable)', null=True)),
                ('date_rejected', models.DateTimeField(blank=True, help_text='Date the offer was rejected (nullable)', null=True)),
                ('multi_doc', models.FileField(blank=True, null=True, upload_to='multi_doc/')),
                ('application', models.ForeignKey(help_text='Foreign key to job_application.id', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='jobs.jobapplication')),
            ],
            options={
                'verbose_name': 'Job Offer',
                'verbose_name_plural': 'Job Offers',
                'db_table': 'job_offer',
                'ordering': ['-date_offered'],
            },
        ),
        migrations.CreateModel(
            name='JobInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_id', models.IntegerField(blank=True, help_text='Foreign key to freelancer_profile.id', null=True)),
                ('interview_date', models.DateTimeField(help_text='Scheduled date and time for the interview')),
                ('interview_mode', models.CharField(choices=[('in-person', 'In-person'), ('zoom', 'Zoom'), ('phone', 'Phone'), ('teams', 'Microsoft Teams'), ('google-meet', 'Google Meet')], help_text='Mode of the interview (In-person, Zoom, etc.)', max_length=20)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rescheduled', 'Rescheduled'), ('No-show', 'No-show')], default='Scheduled', help_text='Interview status (Scheduled, Completed, etc.)', max_length=20)),
                ('interview_notes', models.TextField(blank=True, help_text='Notes from the interview', null=True)),
                ('interview_link', models.URLField(blank=True, help_text='Link for online interviews (Zoom, Teams, etc.)', null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Interview rating from 1 to 5', max_digits=2, null=True)),
                ('comments', models.TextField(blank=True, help_text='Feedback comments from the interview', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date the interview was scheduled')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Date the interview was last updated')),
                ('application', models.ForeignKey(help_text='Foreign key to job_application.id', on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.jobapplication')),
                ('job', models.ForeignKey(blank=True, help_text='Foreign key to job_posting.id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_interviews', to='jobs.jobposting')),
            ],
            options={
                'verbose_name': 'Job Interview',
                'verbose_name_plural': 'Job Interviews',
                'db_table': 'job_interview',
                'ordering': ['-interview_date'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(help_text='Foreign key to job_posting.id', on_delete=django.db.models.deletion.CASCADE, to='jobs.jobposting'),
        ),
        migrations.CreateModel(
            name='ApplicationWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of withdrawal')),
                ('reason', models.TextField(help_text='Reason for withdrawal')),
                ('application', models.OneToOneField(help_text='Foreign key to job_application.id', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal', to='jobs.jobapplication')),
            ],
            options={
                'verbose_name': 'Application Withdrawal',
                'verbose_name_plural': 'Application Withdrawals',
                'db_table': 'application_withdrawal',
                'ordering': ['-withdrawal_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'freelancer_id')},
        ),
    ]
