# Generated by Django 4.2.23 on 2025-12-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(default='Pending', help_text='Application status (Pending, Accepted, Rejected, Save for Later, Withdrawn)', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobinterview',
            name='interview_mode',
            field=models.CharField(help_text='Mode of the interview (In-person, Zoom, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobinterview',
            name='status',
            field=models.CharField(default='Scheduled', help_text='Interview status (Scheduled, Completed, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='offer_status',
            field=models.CharField(default='Pending', help_text='Status of the offer (Pending, Accepted, Rejected)', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='application_method',
            field=models.CharField(default='portal', help_text='Application method', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency', max_length=3),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='interview_mode',
            field=models.CharField(help_text='Interview mode', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_category',
            field=models.CharField(help_text='Job category', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_status',
            field=models.CharField(default='open', help_text='Job status', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_type',
            field=models.CharField(help_text='Job type', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='work_mode',
            field=models.CharField(help_text='Mode of work', max_length=20),
        ),
    ]
