# Generated by Django 4.2.23 on 2025-12-28 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_alter_jobapplication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User assigned to manage this job posting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='reference_added_by_admin',
            field=models.TextField(blank=True, help_text='Internal reference or note added by admin', null=True),
        ),
    ]
