# Generated by Django 4.2.23 on 2025-12-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobposting_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='reference_added_by_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
