# Generated by Django 4.2.23 on 2025-12-16 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('project', 'Project'), ('job', 'Job')], max_length=20)),
                ('reference_id', models.PositiveIntegerField()),
                ('reference_title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('payment', 'Payment Issue'), ('project', 'Project Issue'), ('job', 'Job Issue'), ('service', 'Service Question'), ('other', 'Other')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('messages', models.JSONField(blank=True, default=list, help_text='\n        Example:\n        [\n          {\n            "sender": "user",\n            "sender_id": 5,\n            "message": "I need help",\n            "timestamp": "2025-12-17T10:15:00Z"\n          }\n        ]\n        ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
