# Generated by Django 4.2.23 on 2025-12-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportticketnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='messages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='SupportTicketNote',
        ),
    ]
